<?php
namespace Satusehat\IntegrationSdk;
final class Config {
 public const SANDBOX_OAUTH='https://api-satusehat-stg.dto.kemkes.go.id/oauth2/v1'; public const SANDBOX_FHIR='https://api-satusehat-stg.dto.kemkes.go.id/fhir-r4/v1'; public const PRODUCTION_OAUTH='https://api-satusehat.kemkes.go.id/oauth2/v1'; public const PRODUCTION_FHIR='https://api-satusehat.kemkes.go.id/fhir-r4/v1';
 public function __construct(public string $clientId,public string $clientSecret,public string $organizationId,public string $environment='sandbox',public string $queuePath='./satusehat-sdk.db',public int $timeoutSeconds=30,public int $rateLimitRpm=300,public int $maxRetries=5,public int $initialBackoffMs=1000,public int $maxBackoffMs=60000,public ?string $oauthBaseUrlOverride=null,public ?string $fhirBaseUrlOverride=null){if(!in_array($environment,['sandbox','production'],true))throw new \InvalidArgumentException('environment must be sandbox or production');if($clientId===''||$clientSecret===''||$organizationId==='')throw new \InvalidArgumentException('credentials and organizationId required');}
 public function oauthBaseUrl():string{return rtrim($this->oauthBaseUrlOverride ?? ($this->environment==='production'?self::PRODUCTION_OAUTH:self::SANDBOX_OAUTH),'/');}
 public function fhirBaseUrl():string{return rtrim($this->fhirBaseUrlOverride ?? ($this->environment==='production'?self::PRODUCTION_FHIR:self::SANDBOX_FHIR),'/');}
 private static function envInt(string $k,int $d):int{$v=getenv($k);return $v===false?$d:(int)$v;}
 public static function fromEnv():self{return new self((string)getenv('SATUSEHAT_CLIENT_ID'),(string)getenv('SATUSEHAT_CLIENT_SECRET'),(string)getenv('SATUSEHAT_ORGANIZATION_ID'),strtolower((string)(getenv('SATUSEHAT_ENV')?:'sandbox')),(string)(getenv('SATUSEHAT_QUEUE_PATH')?:'./satusehat-sdk.db'),self::envInt('SATUSEHAT_TIMEOUT_SECONDS',30),self::envInt('SATUSEHAT_RATE_LIMIT_RPM',300),self::envInt('SATUSEHAT_MAX_RETRIES',5),self::envInt('SATUSEHAT_INITIAL_BACKOFF_MS',1000),self::envInt('SATUSEHAT_MAX_BACKOFF_MS',60000),getenv('SATUSEHAT_OAUTH_BASE_URL')?:null,getenv('SATUSEHAT_FHIR_BASE_URL')?:null);}
}
