<?php
namespace Satusehat\IntegrationSdk;
enum EventStatus:string {case QUEUED='QUEUED';case PROCESSING='PROCESSING';case SUCCESS='SUCCESS';case WAITING_FOR_CORRECTION='WAITING_FOR_CORRECTION';case RATE_LIMITED='RATE_LIMITED';case RETRYING='RETRYING';case DEAD_LETTER='DEAD_LETTER';case CANCELLED='CANCELLED';}
