namespace Satusehat.IntegrationSdk;
public sealed record SatusehatConfig(string ClientId,string ClientSecret,string OrganizationId,string Environment="sandbox",string QueuePath="./satusehat-sdk.db",int TimeoutSeconds=30,int RateLimitRpm=300,int MaxRetries=5,int InitialBackoffMs=1000,int MaxBackoffMs=60000,string? OAuthBaseUrlOverride=null,string? FhirBaseUrlOverride=null)
{
 public const string SandboxOAuth="https://api-satusehat-stg.dto.kemkes.go.id/oauth2/v1",SandboxFhir="https://api-satusehat-stg.dto.kemkes.go.id/fhir-r4/v1",ProductionOAuth="https://api-satusehat.kemkes.go.id/oauth2/v1",ProductionFhir="https://api-satusehat.kemkes.go.id/fhir-r4/v1";
 public string OAuthBaseUrl => (OAuthBaseUrlOverride ?? (Environment=="production"?ProductionOAuth:SandboxOAuth)).TrimEnd('/');
 public string FhirBaseUrl => (FhirBaseUrlOverride ?? (Environment=="production"?ProductionFhir:SandboxFhir)).TrimEnd('/');
 public void Validate(){if(Environment != "sandbox" && Environment != "production")throw new ArgumentException("environment must be sandbox or production");if(string.IsNullOrWhiteSpace(ClientId)||string.IsNullOrWhiteSpace(ClientSecret)||string.IsNullOrWhiteSpace(OrganizationId))throw new ArgumentException("credentials and organizationId required");if(RateLimitRpm<=0||MaxRetries<=0)throw new ArgumentException("rate limit and max retries must be > 0");}
 static int EnvInt(string k,int d)=>int.TryParse(System.Environment.GetEnvironmentVariable(k),out var v)?v:d;
 public static SatusehatConfig FromEnvironment()=>new(System.Environment.GetEnvironmentVariable("SATUSEHAT_CLIENT_ID")??"",System.Environment.GetEnvironmentVariable("SATUSEHAT_CLIENT_SECRET")??"",System.Environment.GetEnvironmentVariable("SATUSEHAT_ORGANIZATION_ID")??"",(System.Environment.GetEnvironmentVariable("SATUSEHAT_ENV")??"sandbox").ToLowerInvariant(),System.Environment.GetEnvironmentVariable("SATUSEHAT_QUEUE_PATH")??"./satusehat-sdk.db",EnvInt("SATUSEHAT_TIMEOUT_SECONDS",30),EnvInt("SATUSEHAT_RATE_LIMIT_RPM",300),EnvInt("SATUSEHAT_MAX_RETRIES",5),EnvInt("SATUSEHAT_INITIAL_BACKOFF_MS",1000),EnvInt("SATUSEHAT_MAX_BACKOFF_MS",60000),System.Environment.GetEnvironmentVariable("SATUSEHAT_OAUTH_BASE_URL"),System.Environment.GetEnvironmentVariable("SATUSEHAT_FHIR_BASE_URL"));
}
