import Database from 'better-sqlite3';
import { randomUUID } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { EventStatus } from './errors.js';
const ddl=`CREATE TABLE IF NOT EXISTS integration_events(event_id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,idempotency_key TEXT,operation TEXT NOT NULL,resource_type TEXT NOT NULL,resource_id TEXT,payload_json TEXT,status TEXT NOT NULL,attempt INTEGER NOT NULL DEFAULT 0,http_status INTEGER,error_category TEXT,error_message TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,next_retry_at TEXT);CREATE INDEX IF NOT EXISTS idx_integration_events_ready ON integration_events(status,next_retry_at,created_at);CREATE UNIQUE INDEX IF NOT EXISTS idx_integration_events_idempotency ON integration_events(organization_id,idempotency_key) WHERE idempotency_key IS NOT NULL;`;
const now=()=>new Date().toISOString();
export class SQLiteQueue{
 constructor(path,processingTimeoutSeconds=300){mkdirSync(dirname(path),{recursive:true});this.processingTimeoutSeconds=processingTimeoutSeconds;this.db=new Database(path);this.db.pragma('journal_mode = WAL');this.db.exec(ddl);this.migrate()}
 close(){this.db.close()}
 migrate(){const cols=new Set(this.db.prepare(`PRAGMA table_info(integration_events)`).all().map(r=>r.name));if(!cols.has('idempotency_key'))this.db.exec(`ALTER TABLE integration_events ADD COLUMN idempotency_key TEXT`);this.db.exec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_integration_events_idempotency ON integration_events(organization_id,idempotency_key) WHERE idempotency_key IS NOT NULL`)}
 enqueue(org,operation,rt,id,payload,idempotencyKey){const op=operation.toUpperCase();if(!['GET','POST','PUT','PATCH'].includes(op))throw new Error('unsupported operation');if(['PUT','PATCH'].includes(op)&&!id)throw new Error('resourceId required for PUT/PATCH');const key=idempotencyKey?String(idempotencyKey).trim():null;if(key){const existing=this.db.prepare(`SELECT event_id FROM integration_events WHERE organization_id=? AND idempotency_key=?`).get(org,key);if(existing)return existing.event_id}const eid=randomUUID(),n=now();try{this.db.prepare(`INSERT INTO integration_events(event_id,organization_id,idempotency_key,operation,resource_type,resource_id,payload_json,status,attempt,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,0,?,?)`).run(eid,org,key,op,rt,id??null,payload==null?null:JSON.stringify(payload),EventStatus.QUEUED,n,n)}catch(e){if(key){const existing=this.db.prepare(`SELECT event_id FROM integration_events WHERE organization_id=? AND idempotency_key=?`).get(org,key);if(existing)return existing.event_id}throw e}return eid}
 ready(limit){const n=now();return this.db.prepare(`SELECT * FROM integration_events WHERE (status IN ('QUEUED','RETRYING','RATE_LIMITED') AND (next_retry_at IS NULL OR next_retry_at<=?)) OR (status='PROCESSING' AND next_retry_at IS NOT NULL AND next_retry_at<=?) ORDER BY created_at LIMIT ?`).all(n,n,limit)}
 markProcessing(id){const n=now(),leaseUntil=new Date(Date.now()+this.processingTimeoutSeconds*1000).toISOString();this.db.prepare(`UPDATE integration_events SET status='PROCESSING',attempt=attempt+1,updated_at=?,next_retry_at=? WHERE event_id=?`).run(n,leaseUntil,id);return Number(this.db.prepare(`SELECT attempt FROM integration_events WHERE event_id=?`).get(id).attempt)}
 complete(id,status,httpStatus=null,category=null,message=null,nextRetryAt=null){this.db.prepare(`UPDATE integration_events SET status=?,http_status=?,error_category=?,error_message=?,updated_at=?,next_retry_at=? WHERE event_id=?`).run(status,httpStatus,category,message?String(message).slice(0,2000):null,now(),nextRetryAt,id)}
 get(id){return this.db.prepare(`SELECT * FROM integration_events WHERE event_id=?`).get(id)}
 stats(){const out=Object.fromEntries(Object.values(EventStatus).map(s=>[s,0]));for(const row of this.db.prepare(`SELECT status,COUNT(*) AS n FROM integration_events GROUP BY status`).all())out[row.status]=Number(row.n);return out}
 deadLetters(limit=50){return this.db.prepare(`SELECT * FROM integration_events WHERE status=? ORDER BY updated_at DESC LIMIT ?`).all(EventStatus.DEAD_LETTER,limit)}
 requeue(id){const r=this.db.prepare(`UPDATE integration_events SET status=?,attempt=0,http_status=NULL,error_category=NULL,error_message=NULL,updated_at=?,next_retry_at=NULL WHERE event_id=? AND status IN (?,?,?)`).run(EventStatus.QUEUED,now(),id,EventStatus.DEAD_LETTER,EventStatus.WAITING_FOR_CORRECTION,EventStatus.CANCELLED);return r.changes>0}
}
